### ISSUE TITLE
How long did you get the dataset access?

### ISSUE THREAD

**Issue by wdkwyf** [xmba15/rail_marking#1]
Hi, your project is awesome and I want to follow it up. However, I wait for a long time after I apply the access of dataset....
So I wonder how long did you get the access approved? Thank you very much.

Also wonder which device do you use to get the 'reach 40fps'?

**Comment by xmba15** [comment]
Hi @wdkwyf I remembered I had to also directly email the owner of railsem19 to urge him to send me the url to download the dataset. He sent me the url right after that.

The inference was tested on a GeForce GTX 1080 Ti. With later generation of GPU, I believe the fps will be much higher.

**Comment by wdkwyf** [comment]
Thank you @xmba15.

**Comment by Adeel-Intizar** [comment]
Hi @wdkwyf @xmba15  , i have requested for the link to download the dataset but  it is taking too long, can you kindly share your dataset ?
Thank you
