### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by aleksandra-kim** [xmba15/rail_marking#11]
This might not be the best place to ask this but I couldn't find a better way. I forked your code for a [hackathon project](https://github.com/Acrosicious/Hackzurich2022-Trains), specifically for a [Siemens challenge](https://hackzurich.siemens.cool/#/SMO_Challenge) within [HackZurich2022](https://hackzurich.com/). We used an MIT license for our project in order for the code to be available for use later. Would you agree to also license your code with an open source license like MIT? We would be very grateful!

**Comment by xmba15** [comment]
@aleksandra-kim I added a MIT license. Good luck with the hackathon.

**Comment by aleksandra-kim** [comment]
@xmba15 this is great, thank you!
