### ISSUE TITLE
Do you have a lisence?

### ISSUE THREAD

**Issue by dogooooo** [xmba15/rail_marking#17]
I would like to cite your code in my thesis. If I were to put your work in my references, how would I write it?

**Comment by xmba15** [comment]
@dogooooo This repository is created with MIT license. But please remember the [Railsem19](https://wilddash.cc/license/railsem19) data is provided with [CC-BY-NC 4.0 license](https://creativecommons.org/licenses/by-nc/4.0/)

I created a Zenodo release [HERE](https://zenodo.org/record/7982032). Can you cite it with your academic thesis with that?

**Comment by xmba15** [comment]
Something similar to this

```bash
Ba Tran. (2023). xmba15/rail_marking: v0.0.1 (v0.0.1). Zenodo. https://doi.org/10.5281/zenodo.7982032
```

**Comment by dogooooo** [comment]
> Something similar to this
> 
> ```shell
> Ba Tran. (2023). xmba15/rail_marking: v0.0.1 (v0.0.1). Zenodo. https://doi.org/10.5281/zenodo.7982032
> ```

Ok, I have viewed and downloaded the code you uploaded on Zenodo and I will cite it in my academic thesis, thanks!
